### ISSUE TITLE
not building on Ubuntu 16.04

### ISSUE THREAD

**Issue by TheTesla** [viennacl/pyviennacl-dev#41]
$ sudo -H setup.py install

external/boost-python-ublas-subset/boost_subset/libs/thread/src/pthread/thread.cpp:146:88: error: no matching function for call to ‘call_once(pyviennaclboost::once_flag&, void (&)())’

**Comment by LeeKeyu** [comment]
Got the same error when trying to build on Ubuntu16.04. Has anyone got solution for this?
